### ISSUE TITLE
ip-tor Shouldn't run without root

### ISSUE THREAD

**Issue by Bendahon** [Naategh/Funny-Scripts#1]
When you try and install the tor-service its locked. You could do something like:
#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi
credit: https://askubuntu.com/questions/15853/how-can-a-script-check-if-its-being-run-as-root

**Comment by Naategh** [comment]
Done!
Thanks for reporting this.
If it's ok you can close this issue.
